### ISSUE TITLE
Cannot download the example data

### ISSUE THREAD

**Issue by Tausc** [dendenxu/mipnerf360-pytorch-minus#2]
Hello! I try to download the example data, but failed in both link you provided. It seems that the link is due. Can you provide a new one?
![image](https://github.com/dendenxu/mipnerf360-pytorch-minus/assets/50770432/8e96b320-0dff-49f8-b090-82e445e4283a)
![image](https://github.com/dendenxu/mipnerf360-pytorch-minus/assets/50770432/c0ed8e2b-9316-43e8-963b-e4c729cc4a09)

**Comment by dendenxu** [comment]
https://zjueducn-my.sharepoint.com/:f:/g/personal/3180105504_zju_edu_cn/Eq_Oad5ZoRxJmyOD-9z6BpcB6bwL1dnHgfP7ZOD7hV-XYw
Hi! Could you check if the above link works? I updated the expiration date but the original link just doesn't seem to work.

**Comment by dendenxu** [comment]
Hi! I updated the expiration date, could you check if the link works now?

**Comment by Tausc** [comment]
It works now! Thank you
